# Generated by Django 6.0.5 on 2026-06-10 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagIBIGContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_share_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employer_share_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_employee_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_employer_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagibig_rate', to='payroll.deductiontype')),
            ],
            options={
                'db_table': 'pagibig_contribution',
            },
        ),
        migrations.CreateModel(
            name='PhilhealthContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_floor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_ceiling', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_share_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('employer_share_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='philhealth_rate', to='payroll.deductiontype')),
            ],
            options={
                'db_table': 'philhealth_contribution',
            },
        ),
        migrations.CreateModel(
            name='SSSContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('excess_over', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sss_rate', to='payroll.deductiontype')),
            ],
            options={
                'db_table': 'sss_contribution',
            },
        ),
        migrations.CreateModel(
            name='WithHoldingTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('excess_over', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_tax', to='payroll.deductiontype')),
            ],
            options={
                'db_table': 'withholding_tax_bracket',
            },
        ),
    ]
