from .compute_views import ComputePayrollView,ComputePayrollEmployeeView,PayrollResultByPayrunView
from .payroll_views import EarningTypeListView,EarningTypeDetailsView
from .payslip_views import PayslipView,PayslipByPayrunView  
