# Generated by Django 6.0.5 on 2026-06-02 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_login_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
