# Generated by Django 6.0.5 on 2026-06-02 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_name', models.CharField(max_length=50, unique=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deduction_type',
            },
        ),
        migrations.CreateModel(
            name='EarningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_name', models.CharField(max_length=50, unique=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'earning_type',
            },
        ),
        migrations.CreateModel(
            name='OvertimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_name', models.CharField(max_length=50, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'overtime_type',
            },
        ),
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('payroll_type', models.CharField(choices=[('SEMI_MONTLY', 'Semi Montly'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi Weekly')], default='SEMI_MONTHLY', max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payrun',
            },
        ),
        migrations.CreateModel(
            name='PayrollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_worked', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generate_at', models.DateTimeField(auto_now_add=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_results', to='hr.employee')),
                ('payrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='payroll.payrun')),
            ],
            options={
                'db_table': 'payroll_result',
            },
        ),
        migrations.CreateModel(
            name='PayrollOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('overtime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_overtimes', to='payroll.overtimetype')),
                ('payroll_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='payroll.payrollresult')),
            ],
            options={
                'db_table': 'payroll_overtime',
            },
        ),
        migrations.CreateModel(
            name='PayrollEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('earning_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_earnings', to='payroll.earningtype')),
                ('payroll_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='payroll.payrollresult')),
            ],
            options={
                'db_table': 'payroll_earning',
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to='payroll.deductiontype')),
                ('payroll_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payrollresult')),
            ],
            options={
                'db_table': 'payroll_deduction',
            },
        ),
        migrations.CreateModel(
            name='PayrollBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits_types', to='hr.benefittype')),
                ('payroll_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='payroll.payrollresult')),
            ],
            options={
                'db_table': 'payroll_benefit',
            },
        ),
    ]
